apiVersion: v1
kind: Service
metadata:
  name: wallet-web-service
  namespace: wallet-web
spec:
  selector:
    app: wallet-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
